### ISSUE TITLE
Documentation on modules 

### ISSUE THREAD

**Issue by CheweyZ** [retejs/rete#105]
Is it possible to get any documentation on this https://d3-node-editor.readthedocs.io/en/latest/Extras/#modules

Also with modules is it possible to make one module say I named it test then in another block say use the module test rather than need to recreate all the blocks each time

**Comment by Ni55aN** [comment]
I dont have enought time for this. Bsides it will be better to update the documentation after the implemention of the new plugin-based architecture. (Modules will also be a plugin)

> Also with modules is it possible to make one module say I named it test then in another block say use the module test rather than need to recreate all the blocks each time

You can just copy Module data and pass them to new Module node

**Comment by Ni55aN** [comment]
For now there are no examples for the new architecture for the modules, but I prepared an example where the main things are done inside the plug-in and you do not need to worry about the details of their work.

https://github.com/retejs/examples/tree/master/Module

The main difference is that now the data of the modules are stored in a list, rather than nested in the node data, as it was before

**Comment by Ni55aN** [comment]
https://rete.readthedocs.io/en/latest/Plugins/
