### ISSUE TITLE
module nodes

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#128]
Hi, 

is it possible to set up the module node in the same / similar way to how it was in v0.7.4? 

as in how it had the edit button on the node rather than a list on the side of the div?

ive been trying to replicate the setup but I am still not used to how it all works in v1 ! 

I only ask as I have a limited height in my project and there is the possibility of quite a few modules being created so the visible list may get too long which means it wont be viable for me which is why the edit button on the node itself was a perfect solution.

hope this makes sense! 

cheers

**Comment by JMidd91** [comment]
this can prob be closed. i have hacked my way to give me what i desire. i can share it if you want but its prob not the best / a very elegant way of doing things haha

**Comment by Ni55aN** [comment]
Hi! v0.7.4 has not the best option for data representation, since the node data stores the data of the editor.

In the new version, the module data is stored in one list independently, and can be reused, since the node data refers only to their name

You can also use the stack in the same way, changing over which you will edit the modules, but save everything in one list. That is, node.data.module will store the name, not the object `{id: '..', nodes: {}}` as before

**Comment by JMidd91** [comment]
awesome yea thats basically what ive done! thanks for confirming the process
