### ISSUE TITLE
trigger control from worker

### ISSUE THREAD

**Issue by JMidd91** [retejs/rete#153]
Hey,

is there a way to trigger a function that is in a control within a node, from the nodes worker? 

so if the node recieves an input, i can then call/trigger a function that is related to the control of the node to update the controls contents? 

obviously you can send info through data but i need to update a canvas in my control when an input is connected.

hope this makes sense? 

![image](https://user-images.githubusercontent.com/38964969/43448696-7c1bfc82-94a6-11e8-8dc1-98113382e29b.png)

**Comment by Ni55aN** [comment]
```js
worker(node, inputs, outputs) {
    this.editor.nodes.find(n => n.id === node.id).controls;
}
```
It looks bothering, but since the workers are isolated from the presentation, it remains only to access the nodes through the property editor, which is passed to the component when it is registering. Also controls are available by index. Probably in the future it makes sense to change their placement by the key

**Comment by JMidd91** [comment]
ah ok cool, this will do the job! thanks again
