### ISSUE TITLE
Suggestion: snap into a grid

### ISSUE THREAD

**Issue by vjeux** [retejs/rete#185]
If you've used the design tools Quartz Composer or Origami, one of the way they manage rectangles is by snapping them to a grid. In practice it is very helpful as it makes it easier to group different elements on screen in a way that looks good.

For example, you can look at the video here: https://origami.design/tutorials/getting-started/Getting-Started.html

**Comment by Ni55aN** [comment]
[rete-area-plugin](https://github.com/retejs/area-plugin) support this feature but hasn't been documented yet.


```js
editor.use(AreaPlugin, { snap: { size: 16, dynamic: true } });
```

Example: https://jsfiddle.net/Ni55aN/6fd7hy0v/24/

**Comment by vjeux** [comment]
Nice! That's exactly what I had in mind.

**Comment by zHaytam** [comment]
Hello, this feature is perfect!
One question, is it possible to show the grid?

**Comment by zHaytam** [comment]
Nevermind found it. `snap: { background: true, snap: { size: 32, dynamic: true } }`.

**Comment by relu91** [comment]
> Nevermind found it. { background: true, snap: { size: 32, dynamic: true } }.

It seems that the lastest version misses this background feature, is it true or it has been moved somewhere else?

**Comment by Ni55aN** [comment]
@relu91  https://retejs.org/examples/area-extensions

```ts
AreaExtensions.snapGrid(area, {
  size: 20
});
```

**Comment by relu91** [comment]
Thanks, @Ni55aN but I was looking for some automatic way to display the grid. The `background: true` option is not available in the latest version.

**Comment by Ni55aN** [comment]
@relu91 oh, sorry for the misunderstanding (I didn't pay attention to the feature name)

In v1, the background function is part of the area plugin. But since version 2 it has been removed because it's a simple feature that consists of an html element + some css properties, so it can be easily implemented from scratch, as in the example:

https://retejs.org/examples/customization/react
![image](https://github.com/user-attachments/assets/ec6319bd-1177-4a97-a27f-7525fd0c4724)

You can copy these files:
_src/custom-background.ts
background.css_

then add this code after AreaPlugin initialization
```ts
addCustomBackground(area);
```
