### ISSUE TITLE
Engine Freezing

### ISSUE THREAD

**Issue by Kripakaran** [retejs/rete#245]
How do you freeze the rete engine on the clicking of a button. Like a play/pause button

**Comment by Ni55aN** [comment]
There is no built-in ability to pause/resume processing. 

You can modify `worker()` on `componentregister` event. 

Example:
```js
editor.on('componentregister', component => {
  const worker = component.worker;

  component.worker = async () => {
     /// resolve promise there if processing not paused, otherwise add `resolve` method to storage
    await worker(...arguments);
  }
});
```
Be aware to subscribe on this event before installing of ProfilerPlugin or something else. Order is important

Another case when you use TaskPlugin. It may work differently with it, since it modifies the method
