### ISSUE TITLE
Angular render plugin

### ISSUE THREAD

**Issue by Ni55aN** [retejs/rete#358]

**Comment by Ni55aN** [comment]
I figured out how to render many HTML elements -> @angular/elements. For example, on `rendernode` I can insert `<rete-node></rete-node>` to `el`, where `rete-node` is a custom element (Angular component will be rendered to tag with that name)

Unfortunately I cannot continue development due to StaticInjectorError for locally installed dependencies https://github.com/angular/angular-cli/issues/11199

`preserveSymlinks` doesn't help, checked on Windows 10 and WSL (ubuntu)

**Comment by Ni55aN** [comment]
I'll push the draft to repo

**Comment by Githamza** [comment]
How to reproduce yout error ?

I have done 

- npm i
- npm run build I get error : Module '@angular/compiler' not found

**Comment by Ni55aN** [comment]
> also I don't find angular.json file in project, is it normal ?

yes, ng-packagr don't require that

**Comment by Githamza** [comment]
> yes, ng-packagr doesn't require that

ok, so you have tried `preserveSymlinks` [solution ](https://github.com/angular/angular-cli/issues/11199) inside `ng-package.json` that's it ? Because in the mentioned issue the solution was by using `angular.json` file and `ng build`

**Comment by Ni55aN** [comment]
>  tried preserveSymlinks solution inside ng-package.json

No, I used this in the application's angular.json

**Comment by Ni55aN** [comment]
So far, I have not found a way to make this work through the installation of a local package. 
There are that  it works on version 5, my in my case (ver 7) its not working.

 This is one of the reasons why I do not recommend using Angular.

**Comment by Ni55aN** [comment]
The first version of this plugin has been released [v0.1.0](https://www.npmjs.com/package/rete-angular-render-plugin)

Example: https://github.com/retejs/examples/tree/master/Angular/src

**Comment by Githamza** [comment]
Great job !

**Comment by testermax** [comment]
Hi,
First: Im impressed by the rete library and I think that it is really useful! 
I have been playing around a little bit with it in an angular 8 application. I sue the vue-renderer, but I would like to not reference any vue inside my application. So I tested the angular-render-plugin (0.1.0).
I have built my example on the rete/examples/angular project and bumped to version 8 of angular. When I build the project, I get the following:
ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 13970:30-43
"export 'jitExpression' was not found in '@angular/compiler'
ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 13995:32-45
"export 'jitExpression' was not found in '@angular/compiler'
ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 14238:33-46
"export 'jitExpression' was not found in '@angular/compiler'
ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 14287:33-46
"export 'jitExpression' was not found in '@angular/compiler'
ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 14491:22-35
"export 'jitExpression' was not found in '@angular/compiler'
ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 14568:28-41
"export 'jitExpression' was not found in '@angular/compiler'
ERROR in ./src/polyfills.ts


Is this due to the new compiler in angular 8 or is it something in the rete-angular-library?

It would be really nice to have a working angular 8 example with the rete-angular-render-plugin.

**Comment by Githamza** [comment]
> Hi,
> First: Im impressed by the rete library and I think that it is really useful!
> I have been playing around a little bit with it in an angular 8 application. I sue the vue-renderer, but I would like to not reference any vue inside my application. So I tested the angular-render-plugin (0.1.0).
> I have built my example on the rete/examples/angular project and bumped to version 8 of angular. When I build the project, I get the following:
> ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 13970:30-43
> "export 'jitExpression' was not found in '@angular/compiler'
> ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 13995:32-45
> "export 'jitExpression' was not found in '@angular/compiler'
> ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 14238:33-46
> "export 'jitExpression' was not found in '@angular/compiler'
> ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 14287:33-46
> "export 'jitExpression' was not found in '@angular/compiler'
> ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 14491:22-35
> "export 'jitExpression' was not found in '@angular/compiler'
> ERROR in ./node_modules/rete-angular-render-plugin/node_modules/@angular/core/fesm2015/core.js 14568:28-41
> "export 'jitExpression' was not found in '@angular/compiler'
> ERROR in ./src/polyfills.ts
> 
> Is this due to the new compiler in angular 8 or is it something in the rete-angular-library?
> 
> It would be really nice to have a working angular 8 example with the rete-angular-render-plugin.

try to retrograde to angular 7 ?

**Comment by testermax** [comment]
Im not sure what you mean by :
> try to retrograde to angular 7 ?

You mean going back to angular 7?
If so, that is not what I want, I want to be on version 8, and later this year on 9.

Or do you mean setting som options when I bump from 7 to 8?

**Comment by Githamza** [comment]
> Im not sure what you mean by :
> 
> > try to retrograde to angular 7 ?
> 
> You mean going back to angular 7?
> If so, that is not what I want, I want to be on version 8, and later this year on 9.
> 
> Or do you mean setting som options when I bump from 7 to 8?

May be without using the ivy renderer so juste disable it on v8

**Comment by testermax** [comment]
> May be without using the ivy renderer so just disable it on v8
This did not solve unfortunately, but thanks for the tip.
Have you managed to run the angular-renderer under angular v8?

**Comment by Ni55aN** [comment]
@testermax I will post a version with corresponding dependencies for Angular 8, but I'm not sure how to manage version identifiers for multiple dependencies independently

**Comment by Ni55aN** [comment]
I found one solution: install dependencies as peerDependencies. 

In this way `@angular/core`, etc. will be installed once and the render plugin will use the same as your application

https://www.npmjs.com/package/rete-angular-render-plugin/v/0.1.1

**Comment by testermax** [comment]
@Ni55aN Thank you!
This works like a charm. Fingers crossed this will work in angular 9 as well.

**Comment by Ni55aN** [comment]
@testermax I guess. If this plugin uses a feature from v7, which has major changes in the next version, a crash will occur.

**Comment by Githamza** [comment]
Actual l'm using it and  I get not problem with the plugin

**Comment by WieFel** [comment]
For me, everything works fine since I use the newest version v0.2.0-rc.1 and thus having resolved the issue https://github.com/retejs/angular-render-plugin/issues/7#issue-534525504
