### ISSUE TITLE
[Feature Request] Add control to output

### ISSUE THREAD

**Issue by a7md0** [retejs/rete#471]
Ability to add control(s) to Output of the node just like the Input? This would be useful

**Comment by Hatead1** [comment]
The author says that this is meaningless and not necessary, i have already proposed this. So i have to add this in every new version.

**Comment by Legodev** [comment]
I am not sure if this Issue points in the direction to what i need or if i get it totally wrong... 
But i have the feeling you can answer my question @Hatead1 
Basically what i need is a "Parameter Control/Socket" meaning its an entity which is either a "Control + Output" or "Input + Output"

An example of what i Imagine:
Lets say i have a Node that creates a circles Parameters(X,Y,R), No Input, Output(Circle)
I create a circle A with radius R. 
Now this circles A needs a position, i don't want to have another Node just to provide X+Y, so i would use a control.
How ever now i may have a second circles B which i want to be at the same position as A.
Here it would now be cool to simply have an output for X+Y which i simply can link to the X+Y of B, which of course disables the Control for X+Y on B.

Is there a way to do this, or is this a lose hope, because this is what the author thinks is useless?

**Comment by Hatead1** [comment]
Do you want to have "Input-Control-Output" on one line? You can use "custom" component and standard "Input+Control" & "Output" with positioning on line.

**Comment by Legodev** [comment]
Thank you for that Answer! This sounds like a Plan. :)

**Comment by Hatead1** [comment]
But why you dont want standard controls?
![image](https://user-images.githubusercontent.com/41296890/91829378-10188980-ec4a-11ea-85ec-785190ca49bf.png)

**Comment by Legodev** [comment]
Because they waste to much space for my liking and it does not feel intuitive, specially once the description is hidden when you want to use the control instead of the Input.

Personally i would like to have Input - Description - Control - Output. Where Control shows "linked" or so when the Input is connected.

**Comment by Hatead1** [comment]
https://codepen.io/hatead1/pen/oNxemKo - for example

**Comment by Legodev** [comment]
This is just perfect, thank you very very much! <3
