### ISSUE TITLE
Rete with Svelte/Sapper and Rollup?

### ISSUE THREAD

**Issue by 3daddict** [retejs/rete#490]
Has anyone tried to get Rete implemented on [Svelte](https://svelte.dev/)/[Sapper](https://sapper.svelte.dev/) using [Rollup](https://rollupjs.org/guide/en/)?

Been trying to use this but running into all kinds of issues with importing the required modules. Can't seem to get around the Polyfills error and it would be really nice to breakout rete into svelte components.

Anyone tried this and have an example they can share???

**Comment by pkrogel-kws** [comment]
I've been working on getting Svelte/Rete to play together for the past week or so.  

I initially found [rete-svelte-render-plugin](https://github.com/c0bra/rete-svelte-render-plugin), but it unfortunately did not work right out the gate for me.  With no plugin documentation, and 0 experience with Rete, I figured that since I knew React, I could just work backwards from the official Rete React render plugin to fix whatever the issue was. 

I did get things working, and started to play around with some of the other plugins, and ran into some issues with the Task plugin (probably due to my lack of experience/understanding of Rete).  At that point, I started to feel like the integration between Rete, Svelte, and the Task plugin felt a bit hacky and not very Sveltey when it came to my use case.   

I'm now using Svelte stores for all the IO, and actually dropped the Task plugin all together, as derived stores and potentially RxJs will suffice for my use case.  I've got a few more ideas to try, but It's already feeling pretty nice now, and I'm starting to really enjoy prototyping with Rete and Svelte.

I'm not sure when I'll get around to factoring out some sample code to provide, but I'd be happy to assist further over email or discord if that helps.

**Comment by 3daddict** [comment]
Thanks @pkrogel-kws ya any sample code you have time provide would be really interesting to see. The plugins & lack of docs have been blocking me from getting this to work and breaking things out into Svelte components. Looking forward to a possible update on this in future!

**Comment by Ni55aN** [comment]
Svelte plugin just [has been released](https://twitter.com/rete_js/status/1675577935233703939)
