### ISSUE TITLE
All nodes are duplicated when React renders again (after a click on a Button for example)

### ISSUE THREAD

**Issue by sbstnkll** [retejs/rete#523]
Hi,

I used your exact example at https://codesandbox.io/s/retejs-react-render-t899c?file=/src/index.js

I have implenented a Button with MaterialUI. As soon as I click on it (I think React then re-renderes), or when just another function is called, all nodes get duplicated.

How can I resolve this? Can I wrap the Editor in a React-component?

EDIT:

This is my exact code - codesandbox: [https://codesandbox.io/s/hungry-cray-r2881?file=/src/App.js](https://codesandbox.io/s/hungry-cray-r2881?file=/src/App.js)
(You can replicate the error there - just click on the hamburger button)

<img width="1384" alt="Bildschirmfoto 2021-04-23 um 00 33 03" src="https://user-images.githubusercontent.com/31189168/115792969-83366200-a3cb-11eb-809c-9e6fbd141f18.png">

Thanks, sebastian

**Comment by Ni55aN** [comment]
Since the ref attribute has an inline callback, the `createEditor` function is triggered on every rerender. As the basic example doesn't have rerenders, it is not reproducible.

I have updated an example and added `useRete` hook: https://codesandbox.io/s/retejs-react-render-t899c
I hope it can fix the issue both with the creation of the editor and its destroy on unmount.
