### ISSUE TITLE
Is there any way to select the links/connections between nodes and after selection if we can remove it?

### ISSUE THREAD

**Issue by Kushal616** [retejs/rete#578]
Currently we can remove connections between nodes in editor but for that we need to click on the input socket of node then if we move mouse then that connection can be removed. But I think it will be a lot easier if we can select any connection and then we can delete it using 'Delete' key.

**Comment by Ni55aN** [comment]
It can be implemented as a plugin.

You need to add clickable (transparent) area on `renderconnection` and update it on `renderconnection`. First of all, this is for UX, as the original connection curve is too thin.

**Comment by ArutaGerman** [comment]
> It can be implemented as a plugin.
> 
> You need to add clickable (transparent) area on `renderconnection` and update it on `renderconnection`. First of all, this is for UX, as the original connection curve is too thin.

How to update it? I didn't find the update event

**Comment by ArutaGerman** [comment]
All what I found - this is an events when user clicked on a node socket but not on a connection between nodes. And I can add a class on a connections on `renderconnection`, but how i can get the connection data i don't know, because we can see only DOM-element data - event `click` returned 
`
container: div#rete.node-editor
e: PointerEvent {isTrusted: true, pointerId: 1, width: 1, height: 1, pressure: 0, …}
target: path.main-path
`
