### ISSUE TITLE
Input popup

### ISSUE THREAD

**Issue by demirmehmet0** [retejs/rete#600]
I want to retrieve data using Rete within a popup. In other words, I want to move inputs taken in the node to within the popup. Is there a plugin for this or how can I do it?

**Comment by Ni55aN** [comment]
https://rete.js.org/#/docs/engine#lang=en&tosearch=worker%28node%2C%20inputs

inside Component's worker method you can get input data and open popup

**Comment by demirmehmet0** [comment]
Thanks a lot for the answer, but I don't want the input fields there to appear, I want a popup to open when I double click on the node and I want to enter the content of the input there.

**Comment by Ni55aN** [comment]
```
editor.on('rendernode', ({ el, node }) => {
    node.data // retrieve the node data
    el.addEventListener('dblclick', /* show popup */);
});

**Comment by demirmehmet0** [comment]
Hello, thanks for answer, my goal is to move the inputs in the 2nd field to the 1st field and to remove the 2nd field inputs. I can open modal with double click, but I couldn't find how to move these inputs.
![Ekran Resmi 2023-01-30 13 46 29](https://user-images.githubusercontent.com/56119655/215457275-6568c8b6-0ae9-4d05-8337-40aca799dfe9.png)

**Comment by Ni55aN** [comment]
These inputs (fields) are part of node. In order to "move" them you need to render similar fields using the framework you are using and set its values (received from `node.data`). Then.. remove the controls from 2nd field.
For example, if you are using Vue.js, just render `VueNumControl` (or any other Vue component used for inputs) as in
https://codepen.io/Ni55aN/pen/xzgQYq?editors=0010
