### ISSUE TITLE
Drag and Drop issue

### ISSUE THREAD

**Issue by abinfirmusoft** [retejs/rete#693]
I am looking for the functionality to apply drag and drop nodes from an svg icon from out of the canvas. Can anyone provide an idea of code that helps in implementing the above functionality.

**Comment by arthurwolf** [comment]
I think you might get some helpful code/inspiration from the "dock" plugin.

**Comment by abinfirmusoft** [comment]
Already tried the dock plugin feature, but the results came out as like the image below and it looks weird. I need to add some more nodes and this feature is not applicable for that. 
I am planning to create a box outside the canvas and add svg icons in it. and whenever I drag the svg's to the canvas, a node should get created
![gh](https://github.com/retejs/rete/assets/130958966/a47d1b16-5c47-4617-ab51-41d5a7c5d11b)
 as like in the image

**Comment by abinfirmusoft** [comment]
Yeah, will update here once I cracked it.

**Comment by bullypb23** [comment]
@abin-aloysious @arthurwolf Hey, do you have any update on this one? I am trying to implement the same functionality so if you figure it out, that would be really helpful.

**Comment by abin-aloysious** [comment]
Hi @bullypb23 ,
We can't take the dock menu outside the canvas, so I changed the dock menu to display an icon instead of the full node. This way, the icon will be visible in the dock menu instead of the node. I've attached the image showing the current UI and highlighted the dock menu.
![DOCK](https://github.com/user-attachments/assets/a61ebf53-bc92-4263-b98a-42d4a1e14e34)
