### ISSUE TITLE
Vue 3 reactivity issue with adding inputs/outputs to node

### ISSUE THREAD

**Issue by dlohvinov** [retejs/rete#701]
Вітаю!

I'm having an issue in my Vue 3 application adding new (dynamic) inputs or outputs to a node - they are not reactive :(

The issue is, Vue 3 uses Proxy for tracking reactivity changes, but in `rete` source code, new inputs or outputs are assigned using `Object.defineProperty` ([link](https://github.com/retejs/rete/blob/main/src/presets/classic.ts#L210)), which is not tracked by Proxy reactivity.

If I override this method and just set them like below, everything works fine.
```
addInput(key, input) {
    // super.addInput(key, input);
    this.inputs[key] = input;
  }
```

Is there a reason why `Object.defineProperty` is used, and i should be using my own override solution, or it could be fixed in rete source code?

if you want, i can make a pull request :)

Слава Україні! ❤️

**Comment by dlohvinov** [comment]
It didn't work: new in's/out's hadn't been adding, so I've came up with something like this:

```
  addInput(key, input) {
    // super.addInput(key, input);
    this.height += 50; // each in/out has its own height, so i'm adding it to node height
    this.inputs[key] = input;

// if there's no area inside node - its default node in's/out's on initialization stage
    this.area?.resize(this.id, this.width, this.height);
  }
```

Thanks you for your help! :)

**Comment by Ni55aN** [comment]
It looks like there are other factors rather than a problem with the plugin, because if you test it on [basic example](https://retejs.org/examples/basic/vue), it renders the I/O successfully:

```js
  setTimeout(() => {
    a.addOutput("b", new ClassicPreset.Output(socket));
    area.update('node', a.id)
  }, 4000)
  ```
  
are you using a custom node component? Does it have prop `seed` and `inputs`/`outputs` [as a getter](https://github.com/retejs/vue-plugin/blob/main/src/presets/classic/components/Node.vue#L62), not computed?
